# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KilnProfiler.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from MyWidgets import ImageLabel

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1100, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setStyleSheet("background-color: rgb(175, 255, 211);")
        Dialog.setStyleSheet("QLabel, QPushButton, QCheckBox {font: 30pt Comic Sans MS} QLabel {font: 15pt Comic Sans MS}")
#        Dialog.setStyleSheet("QLabel {font: 15pt Comic Sans MS}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labImage = ImageLabel (Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.labImage.sizePolicy().hasHeightForWidth())
        self.labImage.setSizePolicy(sizePolicy)
        self.labImage.setMinimumSize(QtCore.QSize(320, 200))
        self.labImage.setFrameShape(QtWidgets.QFrame.Panel)
        self.labImage.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.labImage.setLineWidth(2)
        self.labImage.setObjectName("labImage")
        self.horizontalLayout.addWidget(self.labImage)
        self.labClippedImage = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.labClippedImage.sizePolicy().hasHeightForWidth())
        self.labClippedImage.setSizePolicy(sizePolicy)
        self.labClippedImage.setMinimumSize(QtCore.QSize(320, 200))
        self.labClippedImage.setFrameShape(QtWidgets.QFrame.Panel)
        self.labClippedImage.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.labClippedImage.setLineWidth(2)
        self.labClippedImage.setObjectName("labClippedImage")
        self.horizontalLayout.addWidget(self.labClippedImage)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnSettings = QtWidgets.QPushButton(Dialog)
        icon = QtGui.QIcon.fromTheme("Settings")
        self.btnSettings.setIcon(icon)
        self.btnSettings.setObjectName("btnSettings")
        self.horizontalLayout_2.addWidget(self.btnSettings)
        self.lcdNumber = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber.setStyleSheet("background-color: black;")
        self.lcdNumber.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber.setProperty("value", 2095.0)
        self.lcdNumber.setObjectName("lcdNumber")
        self.horizontalLayout_2.addWidget(self.lcdNumber)
        self.labTime = QtWidgets.QLabel(Dialog)
        self.labTime.setObjectName("labTime")
        self.horizontalLayout_2.addWidget(self.labTime)
        self.labMsg = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labMsg.sizePolicy().hasHeightForWidth())
        self.labMsg.setSizePolicy(sizePolicy)
        self.labMsg.setObjectName("labMsg")
        self.horizontalLayout_2.addWidget(self.labMsg)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btnPreview = QtWidgets.QCheckBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPreview.sizePolicy().hasHeightForWidth())
        self.btnPreview.setSizePolicy(sizePolicy)
        self.btnPreview.setObjectName("btnPreview")
        self.horizontalLayout_2.addWidget(self.btnPreview)
        self.btnSnap = QtWidgets.QPushButton(Dialog)
        self.btnSnap.setObjectName("btnSnap")
        self.horizontalLayout_2.addWidget(self.btnSnap)
        self.btnSharpen = QtWidgets.QPushButton(Dialog)
        self.btnSharpen.setObjectName("btnSharpen")
        self.horizontalLayout_2.addWidget(self.btnSharpen)
        self.btnRun = QtWidgets.QCheckBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRun.sizePolicy().hasHeightForWidth())
        self.btnRun.setSizePolicy(sizePolicy)
        self.btnRun.setObjectName("btnRun")
        self.horizontalLayout_2.addWidget(self.btnRun)
        self.btnExit = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnExit.sizePolicy().hasHeightForWidth())
        self.btnExit.setSizePolicy(sizePolicy)
        self.btnExit.setObjectName("btnExit")
        self.horizontalLayout_2.addWidget(self.btnExit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Kiln Temperature Profiler"))
        self.labImage.setText(_translate("Dialog", "TextLabel"))
        self.labClippedImage.setText(_translate("Dialog", "TextLabel"))
        self.btnSettings.setText(_translate("Dialog", "Settings"))
        self.labTime.setText(_translate("Dialog", "18:00:05"))
        self.labMsg.setText(_translate("Dialog", "Message"))
        self.btnPreview.setText(_translate("Dialog", "Preview"))
        self.btnSnap.setText(_translate("Dialog", "Snap"))
        self.btnSharpen.setText(_translate("Dialog", "Sharpen"))
        self.btnRun.setText(_translate("Dialog", "Run"))
        self.btnExit.setText(_translate("Dialog", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

